### ISSUE TITLE
Hono: Timeout exceptions on certain data grid operations

### ISSUE THREAD

**Issue by calohmn** [eclipse/packages#107]
When deploying Hono with the data grid based implementation for the Device Connection service, certain cache operations used for the Hono Command & Control feature cause a timeout exception.

Example:
````
java.net.SocketTimeoutException: RemoveIfUnmodifiedOperation{device-connection, key=[B0x033E296169404074..[44], flags=1, connection=172.18.0.30/172.18.0.30:11222} timed out after 60000 ms
	at org.infinispan.client.hotrod.impl.operations.HotRodOperation.run(HotRodOperation.java:176)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
````

**Comment by calohmn** [comment]
There seems to be a bug in Infinispan 9.4, so that the `RemoveIfUnmodifiedOperation` operation invoked on a cache entry that has a `maxIdle` period set (either via the config or via a cache operation parameter) will not finish, causing the `SocketTimeoutException` in the client.

In the Hono helm chart here, the `<expiration max-idle="2419200000" />` entry is causing the issue.
This entry will be obsolete with Hono 1.2.3 because the expiration of relevant cache entries is set on the individual cache operations via the `lifespan` parameter (see https://github.com/eclipse/hono/issues/1998).
