### ISSUE TITLE
[HONO] cannot connect with hono-cli using example credentials

### ISSUE THREAD

**Issue by daFritz84** [eclipse/packages#205]
I cannot connect to the dispatcher via hono-cli.

### Steps to reproduce:
I deployed Hono via the latest helm chart on a okd cluster:
```
helm install --dependency-update -n hono --set prometheus.createInstance=false --set grafana.enabled=false eclipse-hono hono
```

I want connect to the command line client via, so I exposed a route to the dispatch router:
```
oc expose service eclipse-hono-dispatch-router-ext --port=amqp
```

connection the dispatch router fails using the example credentials:
```
java -jar hono-cli-*-exec.jar --hono.client.host=$BACKEND_EP --hono.client.port=80 --hono.client.username=consumer@HONO --hono.client.password=verysecret --spring.profiles.active=receiver --tenant.id=DEFAULT_TENANT

  ______     _ _                  _    _
 |  ____|   | (_)                | |  | |
 | |__   ___| |_ _ __  ___  ___  | |__| | ___  _ __   ___
 |  __| / __| | | '_ \/ __|/ _ \ |  __  |/ _ \| '_ \ / _ \
 | |___| (__| | | |_) \__ \  __/ | |  | | (_) | | | | (_) |
 |______\___|_|_| .__/|___/\___| |_|  |_|\___/|_| |_|\___/
                | |
                |_|

Eclipse Hono Example Client  (v1.6.0)
using Spring Boot  (v2.2.11.RELEASE)

Go to https://www.eclipse.org/hono for more information.


11:22:48.522 [main] INFO  org.eclipse.hono.cli.Application - Starting Application v1.6.0 on SE6208 with PID 4828 (/mnt/c/Users/SES/Downloads/scratchpad/hono-cli-1.6.0-exec.jar started by sseifried in /mnt/c/Users/SES/Downloads/scratchpad)
11:22:48.528 [main] INFO  org.eclipse.hono.cli.Application - The following profiles are active: receiver
11:22:50.694 [main] INFO  org.eclipse.hono.cli.Application - running command line client in role(s): receiver
11:22:52.144 [main] INFO  org.eclipse.hono.cli.Application - Started Application in 5.515 seconds (JVM running for 6.61)
11:22:53.527 [vert.x-eventloop-thread-0] INFO  o.e.h.client.impl.HonoConnectionImpl - max number of attempts [5] to re-connect to server [eclipse-hono-dispatch-router-ext-hono.apps.berta.schrack-seconet.wtf:80, role: unknown] have been made, giving up
11:22:53.533 [vert.x-eventloop-thread-0] INFO  o.e.h.client.impl.HonoConnectionImpl - stopping connection attempt to server [eclipse-hono-dispatch-router-ext-hono.apps.berta.schrack-seconet.wtf:80, role: unknown] due to terminal error
io.vertx.core.VertxException: Disconnected
        at io.vertx.proton.impl.ProtonClientImpl.lambda$null$0(ProtonClientImpl.java:81)
        at io.vertx.proton.impl.ProtonConnectionImpl.fireDisconnect(ProtonConnectionImpl.java:381)
        at io.vertx.proton.impl.ProtonTransport.handleSocketEnd(ProtonTransport.java:95)
        at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:96)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
        at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:349)
        at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$4(VertxHandler.java:152)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:221)
        at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
11:22:53.538 [vert.x-eventloop-thread-0] ERROR org.eclipse.hono.cli.app.Receiver - Error occurred during initialization of receiver: failed to connect
```

### Troubleshooting (I already did):
If I curl the route, I get an appropiate error in the dispatcher logs, so connection should be forwarded ok:
```
curl $BACKEND_EP
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```
**Output:**
```
2021-03-09 10:16:07.037494 +0000 SERVER (info) enabling remote authentication service eclipse-hono-service-auth:5671
2021-03-09 10:16:07.043374 +0000 SERVER (info) [C32] Accepted connection to 0.0.0.0:5672 from 10.131.0.1:49004
2021-03-09 10:16:07.043419 +0000 SERVER (info) [C32] Connection from 10.131.0.1:49004 (to 0.0.0.0:5672) failed: amqp:connection:framing-error Unknown protocol detected: 'GET / HTTP/1.1\x0d\x0aUse...'
```

If I use the hono cli connecting to hono.eclipseprojects.io it works fine:
```
java -jar hono-cli-*-exec.jar --hono.client.host=hono.eclipseprojects.io --hono.client.port=15672 --hono.client.username=consumer@HONO --hono.client.password=verysecret --spring.profiles.active=receiver --tenant.id=DEFAULT_TENANT
```
**Output:**
```

  ______     _ _                  _    _
 |  ____|   | (_)                | |  | |
 | |__   ___| |_ _ __  ___  ___  | |__| | ___  _ __   ___
 |  __| / __| | | '_ \/ __|/ _ \ |  __  |/ _ \| '_ \ / _ \
 | |___| (__| | | |_) \__ \  __/ | |  | | (_) | | | | (_) |
 |______\___|_|_| .__/|___/\___| |_|  |_|\___/|_| |_|\___/
                | |
                |_|

Eclipse Hono Example Client  (v1.6.0)
using Spring Boot  (v2.2.11.RELEASE)

Go to https://www.eclipse.org/hono for more information.


11:20:21.025 [main] INFO  org.eclipse.hono.cli.Application - Starting Application v1.6.0 on SE6208 with PID 4787 (/mnt/c/Users/SES/Downloads/scratchpad/hono-cli-1.6.0-exec.jar started by sseifried in /mnt/c/Users/SES/Downloads/scratchpad)
11:20:21.031 [main] INFO  org.eclipse.hono.cli.Application - The following profiles are active: receiver
11:20:23.189 [main] INFO  org.eclipse.hono.cli.Application - running command line client in role(s): receiver
11:20:24.625 [main] INFO  org.eclipse.hono.cli.Application - Started Application in 5.472 seconds (JVM running for 6.556)
11:20:25.985 [vert.x-eventloop-thread-0] INFO  org.eclipse.hono.cli.app.Receiver - Receiver [tenant: DEFAULT_TENANT, mode: all] created successfully, hit ctrl-c to exit
```

Any help is much appreciated. I'm a little bit lost where to look next. 
How can I check the credentials used for the dispatch router?

**Comment by daFritz84** [comment]
I missed the `--set-platform=openshift` option 😊 Thanks for pointing that out.

From my own ongoing investigations, I found that port forwarding works:
```
oc port-forward eclipse-hono-dispatch-router-699c4c57c7-zt96v :5672
Forwarding from 127.0.0.1:37441 -> 5672
Forwarding from [::1]:37441 -> 5672
Handling connection for 37441
```

However it seems, that amqp via openshift routes is not feasible. As far as I learned from some hastely thrown togethercode , amqp proton is resolving the name to an IP (which, in hindsight totally makes sense for a non-http protocol) and then connects via afore mentioned IP. @calohmn Does this make sense to you?

Btw. passthrough is only needed for encrypted connections (AMQPS, HTTPS). I also tried to model my own route similar to the amqp adapter route:
```
❯ oc describe routes eclipse-hono-dispatch-router-ext
Name:                   eclipse-hono-dispatch-router-ext
Namespace:              hono
Created:                2 hours ago
Labels:                 app.kubernetes.io/component=amqp-messaging-network-router
                        app.kubernetes.io/instance=eclipse-hono
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=hono
                        app.kubernetes.io/version=1.6.0
                        helm.sh/chart=hono-1.5.4
Annotations:            openshift.io/host.generated=true
Requested Host:         eclipse-hono-dispatch-router-ext-hono.apps.berta.schrack-seconet.wtf
                           exposed on router default (host apps.berta.schrack-seconet.wtf) 2 hours ago
Path:                   <none>
TLS Termination:        <none>
Insecure Policy:        <none>
Endpoint Port:          amqp

Service:        eclipse-hono-dispatch-router-ext
Weight:         100 (100%)
Endpoints:      10.129.2.248:5671, 10.129.2.248:5672
```
```
Name:                   eclipse-hono-adapter-amqp-vertx
Namespace:              hono
Created:                2 hours ago
Labels:                 app.kubernetes.io/component=adapter-amqp-vertx
                        app.kubernetes.io/instance=eclipse-hono
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=hono
                        app.kubernetes.io/version=1.6.0
                        helm.sh/chart=hono-1.5.4
Annotations:            meta.helm.sh/release-name=eclipse-hono
                        meta.helm.sh/release-namespace=hono
                        openshift.io/host.generated=true
Requested Host:         eclipse-hono-adapter-amqp-vertx-hono.apps.berta.schrack-seconet.wtf
                           exposed on router default (host apps.berta.schrack-seconet.wtf) 2 hours ago
Path:                   <none>
TLS Termination:        <none>
Insecure Policy:        <none>
Endpoint Port:          amqp

Service:        eclipse-hono-adapter-amqp-vertx
Weight:         100 (100%)
Endpoints:      10.131.0.77:5671, 10.131.0.77:5672
```

**Comment by daFritz84** [comment]
Hi, 

so @calohmn you are correct, TLS passthrough has to be enabled. Otherwise SNI for non-http protocols does not work with openshift/okd (see also https://github.com/openshift/origin/issues/3415 as a reference). Using TLS is a workaround, guess you learn something new every day 😄 

with TLS in place, I can see the connection attempts of the hono-cli client in the dispatcher logs using the following command:
```
java -jar hono-cli-*-exec.jar --hono.client.host=$BACKEND_EP --hono.client.port=443 --hono.client.tlsEnabled=true --hono.client.username=consumer@HONO --hono.client.password=verysecret --spring.profiles.active=receiver --tenant.id=DEFAULT_TENANT
``` 
**Logs**
```
2021-03-10 08:13:35.443057 +0000 SERVER (info) [C62] Accepted connection to 0.0.0.0:5671 from 10.131.0.1:41062
2021-03-10 08:13:35.447664 +0000 SERVER (info) [C62] Connection from 10.131.0.1:41062 (to 0.0.0.0:5671) failed: amqp:connection:framing-error SSL Failure: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
```
I still need to figure out how and which of the demo certificates I need to provide to hono-cli.

**Comment by calohmn** [comment]
I've done a test using a local CodeReady Containers instance (OpenShift 4.7).
I've updated the `charts/hono/example/ca_opts` file first, adding the host of the dispatch router route:
````
subjectAltName = DNS.1:hono-dispatch-router,DNS.2:hono-dispatch-router.hono,DNS.3:eclipse-hono-dispatch-router-hono.apps-crc.testing,DNS.4:localhost
````
Then I've re-created the certificates via the `create_certs.sh` script and deployed hono via:
````
$ helm install --dependency-update -n hono --set platform=openshift eclipse-hono ./charts/hono
````
Then I've started the CLI like this:
````
java -jar <path>/hono-cli-1.6.0-exec.jar
--hono.client.host=eclipse-hono-dispatch-router-hono.apps-crc.testing
--hono.client.port=443 --hono.client.tlsEnabled=true
--hono.client.username=consumer@HONO --hono.client.password=verysecret
--spring.profiles.active=receiver,trace --tenant.id=DEFAULT_TENANT
--hono.client.trustStorePath=charts/hono/example/certs/trusted-certs.pem
````
With that, the qdrouter connection works. It's of course a bit strange to use port 443 instead of 5671 here. I haven't looked into that yet.

**Comment by daFritz84** [comment]
yepp, that worked for me as well. Thank you so much for your assistence. 😄 

I don't know why it didn't work out for me when deploying the recreated certs. Probably I should have done a fresh start instead of messing around with a half broken deployment. One thing I definetely did wrong was using the qdrouter-cert.pem as trustStore.

Regarding the use of 5671 instead of 443: AFAIK you need to create a separate ingress controller which serves port 5671. Then you can assign the routes to this controller using labels. I will look into this as well, maybe I can come up with a solution.

Before I close this topic, would it make sense to put the gist of this thread in a separate openshift-readme markdown file to enhance documentation? I would prepare a pull-request then.

**Comment by calohmn** [comment]
> Before I close this topic, would it make sense to put the gist of this thread in a separate openshift-readme markdown file to enhance documentation? I would prepare a pull-request then.

Sorry for replying late. Yes, that would be good. Instead of creating a separate file you could also add a chapter in the  Hono [readme](https://github.com/eclipse/packages/blob/master/charts/hono/README.md) - or add a link to the separate page there.

**Comment by sophokles73** [comment]
@daFritz84 can this issue be closed?

**Comment by daFritz84** [comment]
@sophokles73 Yes, the issue can be closed.
I never found the time to work on a pull-request enhancing the hono documentation, and now I don't remember all the nitty-gritty details.

Again, thanks for the support.
