### ISSUE TITLE
[Hono] Native image based Command Router fails to start

### ISSUE THREAD

**Issue by sophokles73** [eclipse/packages#231]
The Quarkus native image based Command Router fails to start when using the default embedded cache.
Increasing the log level to DEBUG reveals that Infinispan cannot instantiate the class implementing the single file persistence strategy:
```
2021-05-12 08:26:05,902 DEBUG [org.inf.cac.imp.CacheImpl] (vert.x-worker-thread-0) Started cache org.infinispan.CONFIG on null
2021-05-12 08:26:05,904 DEBUG [org.inf.com.uti.ServiceFinder] (vert.x-worker-thread-0) No service impls found: FilterIndexingServiceProvider
2021-05-12 08:26:05,905 DEBUG [org.inf.per.man.PersistenceManagerImpl] (vert.x-worker-thread-0) PersistenceManagerImpl encountered an exception during startup of stores: java.util.concurrent.CompletionException: org.infinispan.commons.CacheConfigurationException: ISPN000355: Unable to instantiate loader/writer instance for StoreConfiguration class org.infinispan.configuration.cache.SingleFileStoreConfiguration
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: org.infinispan.commons.CacheConfigurationException: ISPN000355: Unable to instantiate loader/writer instance for StoreConfiguration class org.infinispan.configuration.cache.SingleFileStoreConfiguration
	at org.infinispan.persistence.internal.PersistenceUtil.createStoreInstance(PersistenceUtil.java:194)
	at org.infinispan.persistence.support.ComposedSegmentedLoadWriteStore.startNewStoreForSegment(ComposedSegmentedLoadWriteStore.java:250)
	at org.infinispan.persistence.support.ComposedSegmentedLoadWriteStore.start(ComposedSegmentedLoadWriteStore.java:239)
	at org.infinispan.persistence.support.NonBlockingStoreAdapter.lambda$start$0(NonBlockingStoreAdapter.java:108)
	at org.infinispan.util.concurrent.BlockingManagerImpl.lambda$runBlockingOperation$2(BlockingManagerImpl.java:117)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 5 more
```

**Comment by sophokles73** [comment]
The issue here seems to be that Infinispan tries to instantiate the class via reflection but is not able to find the class on the classpath. This needs to be fixed in Hono where the corresponding class(es) need(s) to be explicitly configured for reflection during the native image build.
