### ISSUE TITLE
[Hono] Qpid router cannot connect to Artemis broker

### ISSUE THREAD

**Issue by calohmn** [eclipse/packages#383]
When installing the current Hono chart version and using the AMQP messaging network example, sending of Hono `event` messages fails.
In the Qpid router logs there are such entries:
```
SERVER (info) [C36] Connection to eclipse-hono-artemis:5671 failed: proton:io Connection reset by peer - disconnected eclipse-hono-artemis:5671
```
and in the Artemis logs, there is:
```
2022-07-07 11:30:23,874 WARN  [io.netty.channel.ChannelInitializer] Failed to initialize a channel. Closing: [id: 0xef84cb73, L:/172.17.0.14:5671 - R:/172.17.0.1:57023]: java.lang.IllegalStateException: Unable to create NettyAcceptor for 0.0.0.0:5671
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyAcceptor.loadJdkSslEngine(NettyAcceptor.java:609) [artemis-server-2.16.0.jar:2.16.0]
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyAcceptor.getSslHandler(NettyAcceptor.java:531) [artemis-server-2.16.0.jar:2.16.0]
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyAcceptor$4.initChannel(NettyAcceptor.java:415) [artemis-server-2.16.0.jar:2.16.0]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.51.Final.jar:4.1.51.Final]
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118) [artemis-commons-2.16.0.jar:2.16.0]
Caused by: java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2108) [java.base:]
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:243) [java.base:]
	at java.base/java.security.KeyStore.load(KeyStore.java:1479) [java.base:]
	at org.apache.activemq.artemis.core.remoting.impl.ssl.SSLSupport.loadKeystore(SSLSupport.java:265) [artemis-core-client-2.16.0.jar:2.16.0]
	at org.apache.activemq.artemis.core.remoting.impl.ssl.SSLSupport.loadKeyManagerFactory(SSLSupport.java:290) [artemis-core-client-2.16.0.jar:2.16.0]
	at org.apache.activemq.artemis.core.remoting.impl.ssl.SSLSupport.loadKeyManagers(SSLSupport.java:278) [artemis-core-client-2.16.0.jar:2.16.0]
	at org.apache.activemq.artemis.core.remoting.impl.ssl.SSLSupport.createContext(SSLSupport.java:161) [artemis-core-client-2.16.0.jar:2.16.0]
	at org.apache.activemq.artemis.core.remoting.impl.ssl.DefaultSSLContextFactory.createSSLContext(DefaultSSLContextFactory.java:64) [artemis-core-client-2.16.0.jar:2.16.0]
	at org.apache.activemq.artemis.core.remoting.impl.ssl.DefaultSSLContextFactory.getSSLContext(DefaultSSLContextFactory.java:35) [artemis-core-client-2.16.0.jar:2.16.0]
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyAcceptor.loadJdkSslEngine(NettyAcceptor.java:604) [artemis-server-2.16.0.jar:2.16.0]
	... 19 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	... 29 more
```

It seems there is an issue with the (recently changed) `charts/hono/example/certs/artemisKeyStore.p12` keystore in combination with the Artemis container.

When I re-create the certificates via the `create_certs.sh` script (using `OpenSSL 1.1.1f`), everything works.

When comparing the certificates, the currently checked-in `artemisKeyStore.p12` contains an extra `Authority Key Identifier` X509v3 extension in its certificates that is not there in the keystore created by my `create_certs.sh` invocation and also not in the previous `artemisKeyStore.p12` version.

Logging into the Artemis container and opening the keystore with the JDK `keytool` shows the same error as above:
```
$ /bin/keytool -list -v -storepass artemiskeys -alias 1 -keystore /run/artemis/split-1/custom/etc/artemisKeyStore.p12
keytool error: java.io.IOException: keystore password was incorrect
java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2108)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at java.base/java.security.KeyStore.getInstance(KeyStore.java:1807)
	at java.base/java.security.KeyStore.getInstance(KeyStore.java:1687)
	at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:910)
	at java.base/sun.security.tools.keytool.Main.run(Main.java:397)
	at java.base/sun.security.tools.keytool.Main.main(Main.java:390)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	... 8 more
```
The Artemis container uses `openjdk 11.0.3 2019-04-16 LTS`, so, a rather old version.

Running the same command on the checked-in keystore using JDK `openjdk version "11.0.15" 2022-04-19` works!

**Comment by calohmn** [comment]
@sophokles73 Did you use OpenSSL 3 when recently re-creating the certificates?

**Comment by calohmn** [comment]
A solution could be to use the newer Artemis image from [artemiscloud.io](https://artemiscloud.io/docs/tutorials/deploybasicimage/) (quay.io/artemiscloud/activemq-artemis-broker).
Some adaptations to the deployment/config are needed for that though.

**Comment by sophokles73** [comment]
@calohmn 
Indeed:
```sh
$ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

I am on an Ubuntu 22.04 system which seems to have this version installed by default. Do you think that is the problem?

**Comment by calohmn** [comment]
At least it seems that the newer OpenSSL version produces a keystore that the old JDK 11 (11.0.3) can't work with, requiring a newer JDK 11 patch version. A similar issue is described [here](https://stackoverflow.com/a/72501767).
I'm currently looking into using the artemiscloud.io Artemis image. That is using JDK 17.
