### ISSUE TITLE
c2e Hono - Adaptor and Command Router Certificates Expired 

### ISSUE THREAD

**Issue by viscreoRyan** [eclipse/packages#472]
I have been using the Cloud2Edge Package for a few weeks now but have started receiving the following error in the Hono Adaptors:
...
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Thu Jun 22 06:33:52 UTC 2023
        at java.base/sun.security.x509.CertificateValidity.valid(Unknown Source)
        at java.base/sun.security.x509.X509CertImpl.checkValidity(Unknown Source)
        at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(Unknown Source)
        at java.base/sun.security.provider.certpath.BasicChecker.check(Unknown Source)
        ... 30 more
...

I believe this has occurred previously (looking back at old issues) but it's not clear to me how to resolve this. Please note I am new to this ecosystem so any guidance to documentation I may have missed is more than welcome. 

Any help would be greatly appreciated.  Thank you!

**Comment by calohmn** [comment]
Recreated certificates are in Hono chart version 2.4.2.
